### ISSUE TITLE
issue in s3.tf

### ISSUE THREAD

**Issue by mavaras** [gchamon/terraform-aws-bucket-antivirus#11]
Hi, i'm facing this issue while using your module.
I don't know if it's about anything concerning my code.

` Error: Incorrect attribute value type
   on .terraform/modules/antivirus.antivirus/terraform-aws-bucket-antivirus-1.1.1/s3.tf line 18, in resource "aws_s3_bucket_policy" "public-antivirus-definitions":
   18:   bucket = aws_s3_bucket.antivirus-definitions
     |----------------
     | aws_s3_bucket.antivirus-definitions is object with 25 attributes
 Inappropriate value for attribute "bucket": string required.`

my code (resources_bucket is the name of my bucket):
if i give no arguments for buckets-to-scan, like buckets-to-scan = [] issue stays.

```
variable "resources_bucket" {}

module "antivirus" {
  source = "gchamon/bucket-antivirus/aws"
  version = "1.1.1"

  buckets-to-scan = [var.resources_bucket.bucket]

  scanner-environment-variables = {
    AV_DELETE_INFECTED_FILES = "False"
  }
  
  allow-public-access = true
}
```

**Comment by gchamon** [comment]
I am not sure how that used to work, or specifically which commit broke it, but `bucket = aws_s3_bucket.antivirus-definitions` should be `bucket = aws_s3_bucket.antivirus-definitions.bucket` in s3.tf

let me try to fix that

**Comment by mavaras** [comment]
Thanks, I'm trying to use your module in my company's infraestructure right now.

**Comment by gchamon** [comment]
this module predates the widespread adoption of Terraform Cloud and, while convenient, would be incompatible with it since it tries to compile the clamav solution natively|

I am also not sure which version the clamav upstream solution is in right now. You might be better served for production purposes with a more up-to-date solution. At least until I can refactor this code, and make it compatible with terraform cloud.

In the meantime check out this module: https://registry.terraform.io/modules/trussworks/s3-anti-virus/aws/2.0.0

I think the best approach would be to deploy the infrastructure separately, and compile the code natively as explained in this module.

**Comment by gchamon** [comment]
in any case I fixed the afflicting issue in /release/v1.1.2 and the plan worked correctly locally

can you check if it is working?

**Comment by mavaras** [comment]
I'll try with it. Thanks for being so quick !

**Comment by mavaras** [comment]
Works fine now, thanks again!
I'll stay in touch if anything
